[package]
name = "paxos-actor"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.12"
actix-rt = "2.2"
log = "0.4"
futures = "0.3"

[dev-dependencies]
env_logger = "0.8"
